services:
  mysql:
    image: mysql:8.0
    container_name: sl_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"

  mongo:
    image: mongo:7
    container_name: sl_mongo
    restart: always
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: sl_rabbit
    restart: always
    ports:
      - "5672:5672"  
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWORD}